export default {
  login: "GlebNgouma",
  id: 74310749,
  node_id: "MDQ6VXNlcjc0MzEwNzQ5",
  avatar_url: "https://avatars.githubusercontent.com/u/74310749?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/GlebNgouma",
  html_url: "https://github.com/GlebNgouma",
  followers_url: "https://api.github.com/users/GlebNgouma/followers",
  following_url:
    "https://api.github.com/users/GlebNgouma/following{/other_user}",
  gists_url: "https://api.github.com/users/GlebNgouma/gists{/gist_id}",
  starred_url: "https://api.github.com/users/GlebNgouma/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/GlebNgouma/subscriptions",
  organizations_url: "https://api.github.com/users/GlebNgouma/orgs",
  repos_url: "https://api.github.com/users/GlebNgouma/repos",
  events_url: "https://api.github.com/users/GlebNgouma/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/GlebNgouma/received_events",
  type: "User",
  site_admin: false,
  name: "Gleb Ngouma",
  company: "T-eSoft",
  blog: "www.t-esoft.com",
  location: "Pointe-Noire (Congo)",
  email: null,
  hireable: null,
  bio: "Développeur React Full Stack avec 3 ans d'expérience dans la maintenance et la création de pages Web. ",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-11-11T14:54:51Z",
  updated_at: "2023-09-27T10:08:42Z",
};

// {
//     "login": "GlebNgouma",
//     "id": 74310749,
//     "node_id": "MDQ6VXNlcjc0MzEwNzQ5",
//     "avatar_url": "https://avatars.githubusercontent.com/u/74310749?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/GlebNgouma",
//     "html_url": "https://github.com/GlebNgouma",
//     "followers_url": "https://api.github.com/users/GlebNgouma/followers",
//     "following_url": "https://api.github.com/users/GlebNgouma/following{/other_user}",
//     "gists_url": "https://api.github.com/users/GlebNgouma/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/GlebNgouma/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/GlebNgouma/subscriptions",
//     "organizations_url": "https://api.github.com/users/GlebNgouma/orgs",
//     "repos_url": "https://api.github.com/users/GlebNgouma/repos",
//     "events_url": "https://api.github.com/users/GlebNgouma/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/GlebNgouma/received_events",
//     "type": "User",
//     "site_admin": false,
//     "name": "Gleb Tristan",
//     "company": "T-eSoft",
//     "blog": "",
//     "location": null,
//     "email": null,
//     "hireable": null,
//     "bio": "Je suis un développeur .Net junior avec une expérience de 1 an . ",
//     "twitter_username": null,
//     "public_repos": 9,
//     "public_gists": 0,
//     "followers": 0,
//     "following": 0,
//     "created_at": "2020-11-11T14:54:51Z",
//     "updated_at": "2023-08-10T12:32:58Z"
// }
